test_ee:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  left_finger_to_left_fingertip_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_finger_to_left_fingertip
    pid: {p: 100.0, i: 0.01, d: 10.0}
