# YAML config file for rosee_plugin control for gazebo. Similar syntax to
# the one used by "official" ros plugin http://gazebosim.org/tutorials/?tut=ros_control
#WARNING: DO NOT USE TAB FOR IDENT YAML FILE: This is not permitted by the YAML spec

heri_real: #robot name
  #Controller for each joint. type now is only JointPositionControllerfor JointVelocityController
  SFB1__SFP1_1_position_controller:
    type: JointPositionController
    joint_name: SFB1__SFP1_1
    pid: {p: 0.3, i: 0.001, d: 0.00005}

  LFB1__LFP1_1_position_controller:
    type: JointPositionController
    joint_name: LFB1__LFP1_1
    pid: {p: 0.3, i: 0.001, d: 0.00005}

  LFB2__LFP2_1_position_controller:
    type: JointPositionController
    joint_name: LFB2__LFP2_1
    pid: {p: 0.3, i: 0.001, d: 0.00005}
    
