# YAML config file for rosee_plugin control for gazebo. Similar syntax to
# the one used by "official" ros plugin http://gazebosim.org/tutorials/?tut=ros_control
#WARNING: DO NOT USE TAB FOR IDENT YAML FILE: This is not permitted by the YAML spec
test_ee: #robot name
  #Controller for each joint. type now is only JointPositionControllerf
  base_to_left_finger_controller:
    type: JointPositionController
    joint_name: base_to_left_finger
    pid: {p: 10.0, i: 0.1, d: 0.5}
  base_to_right_finger1_controller:
    type: JointPositionController
    joint_name: base_to_right_finger1
    pid: {p: 10.0, i: 0.1, d: 0.5}
  base_to_right_finger2_controller:
    type: JointPositionController
    joint_name: base_to_right_finger2
    pid: {p: 10.0, i: 0.1, d: 0.5}
  left_finger_to_left_fingertip_controller:
    type: JointVelocityController
    joint_name: left_finger_to_left_fingertip
    pid: {p: 10.0, i: 0.1, d: 0.5}
  right_finger1_to_right_fingertip1_controller:
    type: JointPositionController
    joint_name: right_finger1_to_right_fingertip1
    pid: {p: 10.0, i: 0.1, d: 0.5}
  right_finger2_to_right_fingertip2_controller:
    type: JointPositionController
    joint_name: right_finger2_to_right_fingertip2
    pid: {p: 10.0, i: 0.1, d: 0.5}
